// Maintenance script: re-fetch self-hosted font subsets from fontsource and
// regenerate assets/css/fonts.css. Run from anywhere: `node scripts/fetch-fonts.mjs`
import { mkdir, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const THEME = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

// Prism 自托管 Latin（Geist）+ 中文常用字集（Noto Sans SC chinese-simplified），
// 系统栈补底。
// 中文人眼对字体一致性极敏感：Geist Latin 配各 OS 自带中文后备字时，
// 字形粗细与渲染差异会被读成「模糊」 —— 上线即收到了这条反馈。
// chinese-simplified 子集 + 单字重（500）= 1.16MB，仍远小于 v1 自托管的
// 4.8MB 思源宋体全集。这是对"放弃自托管"的修正，不是简单回滚。
const jobs = [
  { family: 'geist', weights: [400, 500, 600] },
  // 400（正文）+ 700（标题）。为什么必须两个字重：
  // 只给一个 500 的话，标题的 600 请求会落到 500，浏览器再伪粗体化
  // （font-synthesis）补出假的加粗 —— 中文伪粗体发糊，正是"模糊感"的来源之一。
  // 宁可多 1.17MB，也不要伪粗体。
  { family: 'noto-sans-sc', weights: [400, 700] },
  { family: 'jetbrains-mono', weights: [400, 500] },
];

// 不同字体保留不同子集，集中维护避免散落在解析处。
const KEEP_SUBSETS = {
  geist: new Set(['latin']),
  'noto-sans-sc': new Set(['chinese-simplified', 'latin']),
  'jetbrains-mono': new Set(['latin']),
};

// fontsource 曾经在每个 @font-face 前带 /* latin */ 注释，现在不带了。
// 所以不再靠注释判断子集，而是从文件名里取（latin-400-normal.woff2 → latin）。
// 依赖注释是个已经炸过一次的假设，别再依赖它。
const blockRe = /@font-face\s*{([^}]+)}/g;

async function fetchRetry(url, attempts = 4) {
  let lastErr;
  for (let i = 0; i < attempts; i++) {
    try {
      const res = await fetch(url, { signal: AbortSignal.timeout(30000) });
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      return res;
    } catch (err) {
      lastErr = err;
      await new Promise((r) => setTimeout(r, 800 * (i + 1)));
    }
  }
  throw lastErr;
}

let cssOut = '/* Self-hosted fonts (fontsource subsets, woff2). Generated by scripts/fetch-fonts.mjs.\n'
  + '   Prism 只自托管 Latin；中文走系统栈。 */\n\n';
let total = 0;
let skipped = 0;

for (const job of jobs) {
  const outDir = path.join(THEME, 'static/fonts', job.family);
  const urlPrefix = `/fonts/${job.family}`;
  await mkdir(outDir, { recursive: true });

  const downloads = [];

  for (const weight of job.weights) {
    const cssUrl = `https://cdn.jsdelivr.net/fontsource/css/${job.family}@latest/${weight}.css`;
    const css = await (await fetchRetry(cssUrl)).text();

    let kept = 0;
    for (const m of css.matchAll(blockRe)) {
      const body = m[1];
      const woff2 = body.match(/url\((https:[^)]+?\.woff2)\)/);
      if (!woff2) continue;

      const fileName = path.basename(woff2[1]);
      // 子集名取「字重之前的那一段」：latin-400-normal.woff2 → latin，
      // latin-ext-400-normal.woff2 → latin-ext。
      // 直接按 '-' 切第一段会把 latin-ext 误判成 latin，白下一堆文件。
      const named = fileName.match(/^(.+?)-\d+-normal\.woff2$/);
      const subset = named ? named[1] : fileName.split('-')[0];
      if (!KEEP_SUBSETS[job.family].has(subset)) continue;

      const newBody = body.replace(/src:[^;]+;/, `src: url(${urlPrefix}/${fileName}) format('woff2');`).trim();
      cssOut += `/* ${job.family}-${weight}-${subset} */\n@font-face {\n  ${newBody.replace(/\n/g, '\n  ')}\n}\n\n`;
      downloads.push({ url: woff2[1], dest: path.join(outDir, fileName) });
      kept++;
    }

    if (kept === 0) {
      throw new Error(
        `${cssUrl} 没解析到任何期望的子集（期望 ${[...KEEP_SUBSETS[job.family]].join('/')}）` +
        ` —— fontsource 的输出格式可能又变了，检查 blockRe。`
      );
    }
    console.log(`${job.family} ${weight}: ${kept} subset(s)`);
  }

  const queue = [...downloads];
  const workers = Array.from({ length: 6 }, async () => {
    while (queue.length) {
      const d = queue.shift();
      if (existsSync(d.dest)) { skipped++; continue; }
      const buf = Buffer.from(await (await fetchRetry(d.url)).arrayBuffer());
      await writeFile(d.dest, buf);
      total++;
    }
  });
  await Promise.all(workers);
}

await writeFile(path.join(THEME, 'assets/css/fonts.css'), cssOut);
console.log(`DONE. ${total} new, ${skipped} skipped, fonts.css written.`);
