// Maintenance script: re-fetch self-hosted font subsets from fontsource and
// regenerate assets/css/fonts.css. Run from anywhere: `node scripts/fetch-fonts.mjs`
import { mkdir, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const THEME = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

// Prism 只自托管 Latin：中文走系统栈（苹方 / 鸿蒙 / 微软雅黑 / 思源）。
// v1 自托管了 104 个思源宋体分片共 4.8MB，换无衬线后那份体积只剩负担。
const jobs = [
  { family: 'geist', weights: [400, 500, 600] },
  { family: 'jetbrains-mono', weights: [400, 500] },
];

// 只保留 latin。latin-ext / cyrillic / greek / vietnamese 对本博客无用，
// 留着只会让浏览器多下几个文件。
const KEEP_SUBSETS = new Set(['latin']);

// fontsource 曾经在每个 @font-face 前带 /* latin */ 注释，现在不带了。
// 所以不再靠注释判断子集，而是从文件名里取（latin-400-normal.woff2 → latin）。
// 依赖注释是个已经炸过一次的假设，别再依赖它。
const blockRe = /@font-face\s*{([^}]+)}/g;

async function fetchRetry(url, attempts = 4) {
  let lastErr;
  for (let i = 0; i < attempts; i++) {
    try {
      const res = await fetch(url, { signal: AbortSignal.timeout(30000) });
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      return res;
    } catch (err) {
      lastErr = err;
      await new Promise((r) => setTimeout(r, 800 * (i + 1)));
    }
  }
  throw lastErr;
}

let cssOut = '/* Self-hosted fonts (fontsource subsets, woff2). Generated by scripts/fetch-fonts.mjs.\n'
  + '   Prism 只自托管 Latin；中文走系统栈。 */\n\n';
let total = 0;
let skipped = 0;

for (const job of jobs) {
  const outDir = path.join(THEME, 'static/fonts', job.family);
  const urlPrefix = `/fonts/${job.family}`;
  await mkdir(outDir, { recursive: true });

  const downloads = [];

  for (const weight of job.weights) {
    const cssUrl = `https://cdn.jsdelivr.net/fontsource/css/${job.family}@latest/${weight}.css`;
    const css = await (await fetchRetry(cssUrl)).text();

    let kept = 0;
    for (const m of css.matchAll(blockRe)) {
      const body = m[1];
      const woff2 = body.match(/url\((https:[^)]+?\.woff2)\)/);
      if (!woff2) continue;

      const fileName = path.basename(woff2[1]);
      // 子集名取「字重之前的那一段」：latin-400-normal.woff2 → latin，
      // latin-ext-400-normal.woff2 → latin-ext。
      // 直接按 '-' 切第一段会把 latin-ext 误判成 latin，白下一堆文件。
      const named = fileName.match(/^(.+?)-\d+-normal\.woff2$/);
      const subset = named ? named[1] : fileName.split('-')[0];
      if (!KEEP_SUBSETS.has(subset)) continue;

      const newBody = body.replace(/src:[^;]+;/, `src: url(${urlPrefix}/${fileName}) format('woff2');`).trim();
      cssOut += `/* ${job.family}-${weight}-${subset} */\n@font-face {\n  ${newBody.replace(/\n/g, '\n  ')}\n}\n\n`;
      downloads.push({ url: woff2[1], dest: path.join(outDir, fileName) });
      kept++;
    }

    if (kept === 0) {
      throw new Error(`${cssUrl} 没解析到任何 latin 子集 —— fontsource 的输出格式可能又变了，检查 blockRe。`);
    }
    console.log(`${job.family} ${weight}: ${kept} subset(s)`);
  }

  const queue = [...downloads];
  const workers = Array.from({ length: 6 }, async () => {
    while (queue.length) {
      const d = queue.shift();
      if (existsSync(d.dest)) { skipped++; continue; }
      const buf = Buffer.from(await (await fetchRetry(d.url)).arrayBuffer());
      await writeFile(d.dest, buf);
      total++;
    }
  });
  await Promise.all(workers);
}

await writeFile(path.join(THEME, 'assets/css/fonts.css'), cssOut);
console.log(`DONE. ${total} new, ${skipped} skipped, fonts.css written.`);
