// Maintenance script: re-fetch self-hosted font slices from fontsource and
// regenerate assets/css/fonts.css. Run from anywhere: `node scripts/fetch-fonts.mjs`
import { mkdir, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const THEME = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

const jobs = [
  {
    cssUrl: 'https://cdn.jsdelivr.net/fontsource/css/noto-serif-sc@latest/600.css',
    outDir: `${THEME}/static/fonts/noto-serif-sc`,
    urlPrefix: '/fonts/noto-serif-sc',
    keep: () => true, // keep all unicode-range slices
  },
  {
    cssUrl: 'https://cdn.jsdelivr.net/fontsource/css/jetbrains-mono@latest/400.css',
    outDir: `${THEME}/static/fonts/jetbrains-mono`,
    urlPrefix: '/fonts/jetbrains-mono',
    keep: (comment) => /-latin-/.test(comment) && !/latin-ext/.test(comment),
  },
  {
    cssUrl: 'https://cdn.jsdelivr.net/fontsource/css/jetbrains-mono@latest/500.css',
    outDir: `${THEME}/static/fonts/jetbrains-mono`,
    urlPrefix: '/fonts/jetbrains-mono',
    keep: (comment) => /-latin-/.test(comment) && !/latin-ext/.test(comment),
  },
];

const blockRe = /\/\*\s*([^*]+?)\s*\*\/\s*@font-face\s*{([^}]+)}/g;

async function fetchRetry(url, attempts = 4) {
  let lastErr;
  for (let i = 0; i < attempts; i++) {
    try {
      const res = await fetch(url, { signal: AbortSignal.timeout(30000) });
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      return res;
    } catch (err) {
      lastErr = err;
      await new Promise((r) => setTimeout(r, 800 * (i + 1)));
    }
  }
  throw lastErr;
}

let cssOut = '/* Self-hosted fonts (fontsource slices, woff2). Generated by scripts/fetch-fonts.mjs. */\n\n';
let total = 0;
let skipped = 0;

for (const job of jobs) {
  const css = await (await fetchRetry(job.cssUrl)).text();
  await mkdir(job.outDir, { recursive: true });

  const downloads = [];
  for (const m of css.matchAll(blockRe)) {
    const comment = m[1];
    const body = m[2];
    if (!job.keep(comment)) continue;

    const woff2 = body.match(/url\((https:[^)]+?\.woff2)\)/);
    if (!woff2) continue;
    const fileName = path.basename(woff2[1]);
    const localUrl = `${job.urlPrefix}/${fileName}`;
    const newBody = body
      .replace(/src:[^;]+;/, `src: url(${localUrl}) format('woff2');`)
      .trim();
    cssOut += `/* ${comment} */\n@font-face {\n  ${newBody.replace(/\n/g, '\n  ')}\n}\n\n`;
    downloads.push({ url: woff2[1], dest: `${job.outDir}/${fileName}` });
  }

  const queue = [...downloads];
  const workers = Array.from({ length: 6 }, async () => {
    while (queue.length) {
      const d = queue.shift();
      if (existsSync(d.dest)) { skipped++; continue; }
      const buf = Buffer.from(await (await fetchRetry(d.url)).arrayBuffer());
      await writeFile(d.dest, buf);
      total++;
      if (total % 20 === 0) console.log(`downloaded ${total}`);
    }
  });
  await Promise.all(workers);
  console.log(`${job.cssUrl} -> ${downloads.length} files`);
}

await writeFile(`${THEME}/assets/css/fonts.css`, cssOut);
console.log(`DONE. ${total} new, ${skipped} skipped, fonts.css written.`);
